### ISSUE TITLE
Support for 3.x -- esp Harmony's base/bass & root, and Chord's note

### ISSUE THREAD

**Issue by elliotfreedman** [berteh/musescore-chordsToNotes#10]
Hello,
With a view to expanding upon the generate-notes-from-chords theme, I wonder if 3.x supports all of the element attributes for Harmony and Chord (and other objects)?
As evidenced by this and its result under 3.x, it doesn't look like rootTpc or baseTpc and other attributes re supported.
console.log("got harmony ",text," at time ", time," with root: ",harmony.rootTpc," bass: ",harmony.baseTpc);
Debug: got harmony  Dm  at time  0  with root:  undefined  bass:  undefined

**Comment by marfrance** [comment]
Hi, I have the same problem. Is there a solution?
This plugin is very interesting to me!

**Comment by berteh** [comment]
looks to me like MuseScore has not parsed the chords symbol. Per the instructions, make sure it does before running the plugin, by hitting F2 (transpose to anything) and SHIFT-F2 (to transpose back)... or simply transpose to a prime (or just to the current key) - so nothing is really changed.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806
