### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by denschmitz** [berteh/musescore-chordsToNotes#3]
I'd like to make some modifications:

// todo: use chords.xml to produce voicings and remove the embedded data
// todo: determine staff range and best fit the chord in the range.
// todo: support slash chords to establish base.
// todo: if multiple harmonies exist in a measure, carve up the generated chords
//       people can type chords at every quarter note position in empty measures,
// fix: if a harmony is on anything but the top staff, notes go in top staff. put in appropriate staff
// fix: generated whole notes have wrong note head (solid instead of open)
// todo: consider usefulness of making the notes a different color (medium gray) for reference

I can send back updates if you're interested.

**Comment by berteh** [comment]
Hello @denschmitz 

Yes please, these improvements would be great and I'd gladly merge them here for many to use!

Just no sure chords.xml is the way to go: is the "new" parsing mechanism still using it? Per #2 I think it's not, more info from Marc Sabatella at https://github.com/musescore/MuseScore/pull/382  (and former discussions at http://dev-list.musescore.org/chord-symbol-import-export-td7578124.html)

More documentation on the current chords parsing/rendering in MuseScore: https://docs.google.com/document/d/1Q7LXHDSkQb70xmcyquFSiSv_lGbOXMDwzn_24-n7qJw/edit

Good luck!
Berteh.

**Comment by berteh** [comment]
Hello @denschmitz,
did you get at chance to implement any of the improvements you wanted to?
I'd be happy to integrate them here for others to benefit from.
B.

**Comment by berteh** [comment]
Thanks for your feedback.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806

If you wanna keep using this script be sure to check out if you rather use [improved version](https://github.com/berteh/musescore-chordsToNotes/issues/9#issue-368060822) by @Bacchushlg, with
> * automatic creation of a new staff line (only one initial staff is accepted in the moment)
> * correct chord length according to the distance to the next chord symbol
> * some additional chords and synonyms
