### ISSUE TITLE
does not handle Moll chords correctly

### ISSUE THREAD

**Issue by mirabilos** [berteh/musescore-chordsToNotes#4]
I have a piece of music in which a line is annotated with the chords F, d, g, C.

However, while the F-Dur chord is correct, it inserts a D-Dur chord instead of a D-Moll chord.

**Comment by berteh** [comment]
Dear @mirabilos 

Sorry to read it does not work out of the box for you. Let's find out why!

The sample score in test/Chords-To-Note_Generator_simple-test contains one Moll chord (Am) that is correctly generated. So are the Moll chords in the extreme-test and Chord-Chart in the same directory... so I guess it's not an issue of Moll but an issue of notation not being detected.

In my Musescore (2.0.2) I cannot add a lowercase "d" chord.. it is automatically converted to an uppercase "D" by musescore... which should indeed be interpreted as a D-Dur.  How do you manage to add a lowercase "d" chord?

Would it be acceptable to use the default musescore syntax for chords: F Dm Gm C (for your example)?

**Comment by mirabilos** [comment]
Hi, thanks for the quick reply!

You can either enter the chord as Dm then change the display setting to Full German, or change the setting then enter it as lowercase d.

https://musescore.org/en/handbook/chord-symbols#note-spelling

This is “Style → General... → Chord Symbols, Fretboard Diagrams”, from the documentation.

Apparently, MuseScore does not expose the internal note behind the chord annotation which it parsed, but only the display representation. How unfortunate ☹ Does it offer plugins access to this setting, so you can have various chordSuffixToSemitoneNumbers() functions and select the one to use based on that setting?

**Comment by berteh** [comment]
Didn't know about german notation, thanks for the pointer.

MuseScore actually parses the chords annotations, and it is that internal representation (and not the one manually entered by the user) that I use... and the test file I just added in full german notation (with some Moll chords in lowercase) indeed got the Moll chords intepreted wrong... as Dur (major) chords.
https://github.com/berteh/musescore-chordsToNotes/blob/master/test/Chords-To-Notes_german_notation_test.mscz

Since I rely on the internal MuseScore parsing I'll report the bug there... but don't know how fast it will be fixed.
Do you have any documentation on this notation?

**Comment by berteh** [comment]
But on the other hand when I input the chords in international notation (Gm Cm) and then convert the style to german, these minor chords are displayed "gm cm". Are you sure about the german notation meaning minor by default on lowercase?

**Comment by mirabilos** [comment]
Berteh dixit:

> But on the other hand when I input the chords in international
> notation (Gm Cm) and then convert the style to german, these minor
> chords are displayed "gm cm".

Hmm okay…

> Are you sure about the german notation
> meaning minor by default on lowercase?

Pretty much, considering that we have both upper- and lowercase
and https://de.wikipedia.org/wiki/Akkordsymbol#Alternativen says
it’s a somewhat common way to write them.

I don’t recall my own piano lessons well enough, but I _think_
that’s what I learnt back then as well (I didn’t do piano long
enough, only flute which doesn’t have this of course).

**Comment by berteh** [comment]
reported at https://musescore.org/en/node/99631
feel free to join the discussion there... we'll see how this goes.

**Comment by mirabilos** [comment]
I just revisited this topic (to get the github notification going away ;) and posted there; I think your analysis is right.

**Comment by berteh** [comment]
Thanks for your feedback.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806

If you wanna keep using this script be sure to check out if you rather use [improved version](https://github.com/berteh/musescore-chordsToNotes/issues/9#issue-368060822) by @Bacchushlg, with
> * automatic creation of a new staff line (only one initial staff is accepted in the moment)
> * correct chord length according to the distance to the next chord symbol
> * some additional chords and synonyms
