### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mathieuteissonniere** [berteh/musescore-chordsToNotes#5]
Hi,

I'm all new to GitHub. I'd like to know if and how it's possible to customize your plugin to my will. For example, I'd like it to understand that the symbol "delta" or "triangle" refers directly to a Majord7 chord (with the Musejazz font).

Thanks for this plugin who's really missing today. I'm glad to hear it's gonna be in further developpements of Musescore.

Mathieu

**Comment by berteh** [comment]
Hello @mathieuteissonniere 

You can for sure click on "fork" to create a copy of this repository in your user's github space, then check it out (clone), create a new branch (name it 'jazzsymbols' or anything meaningful), make any relevant change to the code, commit many times on the way, click on 'create pull request' so I get a notification and we can discuss integrating these changes in this core repository for others to use,

Would really like to see this happening; let me know if you need more help.
B.

**Comment by mathieuteissonniere** [comment]
Thanks for your reply,

this is the first time for me so thanks for the advices. I've tried 
several things, and some work, some don't :

I've added the sign "∆" which is only available with the musejazz font 
(by typing "t"). I've also added the sign "-" for the minor third.
I've tried to add a new chord "diminished seventh" as the "diminished 
seventh" already available is not a real seventh chord. So I've pasted 
it, change the degres and change the name but it didn't work. So I 
decide to change the "diminished seventh" already existing by the 
"better one" which is 1, 3, 6, 9 (the diminished seventh is the number "9").

This is where I am right now. Are you satisfied with this and do you 
want me to give this back to you ?

I'd also like to know why the chords typed in the lower Staff of a piano 
show in the upper staff ? Is it posible to modify it ? If not it's not a 
big deal, but as far as it can evolve, I'd be glad to contribute.

Mathieu

**Comment by berteh** [comment]
Thanks for your feedback.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806

If you wanna keep using this script be sure to check out if you rather use [improved version](https://github.com/berteh/musescore-chordsToNotes/issues/9#issue-368060822) by @Bacchushlg, with
> * automatic creation of a new staff line (only one initial staff is accepted in the moment)
> * correct chord length according to the distance to the next chord symbol
> * some additional chords and synonyms
