### ISSUE TITLE
Only Root

### ISSUE THREAD

**Issue by dieselmaxxx** [berteh/musescore-chordsToNotes#8]
The plugin only creates only the root note when i click the button. What can I do against it?

**Comment by berteh** [comment]
Thanks for your feedback.

As a similar feature is being integrated in the main release of MuseScore (finally, great!), I personnaly don't plan on supporting this script further. You are of course free to take over from me if you want to. Kindly let me know: https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806
