### ISSUE TITLE
some improvements (add staff, correct chord length,...)

### ISSUE THREAD

**Issue by Bacchushlg** [berteh/musescore-chordsToNotes#9]
I have worked a little bit on your plug-in:

[chordsToNotes.zip](https://github.com/berteh/musescore-chordsToNotes/files/2459121/chordsToNotes.zip)

some improvements:
- automatic creation of a new staff line (only one initial staff is accepted in the moment)
- correct chord length according to the distance to the next chord symbol
- some additional chords and synonyms (as found in several scores that I tested)

what I did not achieve:
- setting of the new staff line's instrumentId (no idea how to do this)
- remove warning "appendPart: <chords> not found"
- the problem that sometimes all chords of a score need to be "touched" for proper detection

**Comment by berteh** [comment]
Thanks for your feedback.

The [harmony playback feature is now available in MuseScore 3](https://github.com/musescore/MuseScore/pull/5129#issuecomment-601717806), development of this plugin is thus stopped, thanks for you feedback and positive comments in the past.
